function func = poincare_gen(k, m, l0, g, ...
                      l_0, phi_0, ...
                      x_dot_0, y_dot_0,   x_0, y_0)
func = @(l_dot_phi_dot) poincare_simulation(k, m, l0, g, ...
                                            l_dot_phi_dot(1), l_dot_phi_dot(2), ...
                                            l_0, phi_0, ...
                                            x_dot_0, y_dot_0,   x_0, y_0);
end